import { RenderMode, type ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  // The home page is API-backed and must resolve deployment configuration at container runtime.
  // Rendering it on request keeps the image environment-agnostic and avoids build-time API calls.
  { path: '', renderMode: RenderMode.Server },
  { path: 'products', renderMode: RenderMode.Server },
  { path: 'products/:gender/:category', renderMode: RenderMode.Server },
  { path: 'catalog', renderMode: RenderMode.Server },
  { path: 'catalog/:section', renderMode: RenderMode.Server },
  { path: 'catalog/:gender/:category', renderMode: RenderMode.Server },
  { path: 'catalog/:gender/:category/:subcategory', renderMode: RenderMode.Server },
  { path: 'product/:id', renderMode: RenderMode.Server },
  { path: 'brands', renderMode: RenderMode.Server },
  { path: 'cart', renderMode: RenderMode.Server },
  { path: 'checkout', renderMode: RenderMode.Server },
  { path: 'order-result', renderMode: RenderMode.Server },
  { path: 'politika-privatnosti', renderMode: RenderMode.Server },
  { path: 'newsletter/subscribe', renderMode: RenderMode.Server },
  { path: 'newsletter/confirmed', renderMode: RenderMode.Server },
  { path: 'newsletter/invalid', renderMode: RenderMode.Server },
  { path: 'newsletter/unsubscribed', renderMode: RenderMode.Server },
  { path: 'newsletter/subscribe-success', renderMode: RenderMode.Server },
  { path: 'newsletter/subscribe-confirmed', renderMode: RenderMode.Server },
  { path: 'newsletter/subscribe-failed', renderMode: RenderMode.Server },
  { path: 'newsletter/subscribe-error', renderMode: RenderMode.Server },
  { path: 'newsletter/unsubscribe-failed', renderMode: RenderMode.Server },
  { path: 'newsletter/unsubscribe-error', renderMode: RenderMode.Server },
  { path: 'newsletter/unsubscribe', renderMode: RenderMode.Server },
  { path: 'newsletter/unsubscribe/:token', renderMode: RenderMode.Server },
  { path: 'order/verification-failed', renderMode: RenderMode.Server },
  { path: 'order/confirmation/success', renderMode: RenderMode.Server },
  { path: 'order/confirmation/already-confirmed', renderMode: RenderMode.Server },
  { path: 'order/confirmation/expired', renderMode: RenderMode.Server },
  { path: 'order/confirmation/already-delivered', renderMode: RenderMode.Server },
  { path: 'order/confirmation/rejected', renderMode: RenderMode.Server },
  { path: 'order/confirmation/error', renderMode: RenderMode.Server },
  { path: 'orders/verify-failed', renderMode: RenderMode.Server },
  { path: 'order/verify', renderMode: RenderMode.Server },
  { path: 'order/verify/:token', renderMode: RenderMode.Server },
  { path: 'orders/verify', renderMode: RenderMode.Server },
  { path: 'orders/verify/:token', renderMode: RenderMode.Server },
  { path: 'order-confirmation', renderMode: RenderMode.Server },
  { path: 'order-confirmation/:token', renderMode: RenderMode.Server },
  { path: 'confirm-order', renderMode: RenderMode.Server },
  { path: 'confirm-order/:token', renderMode: RenderMode.Server },
  { path: 'admin', renderMode: RenderMode.Server },
  { path: 'admin/**', renderMode: RenderMode.Server },
  { path: '404', renderMode: RenderMode.Server, status: 404 },
  { path: '**', renderMode: RenderMode.Server, status: 404 },
];
